# Generated by Django 4.1.7 on 2023-04-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        ('league', '0002_rename_any_league_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teams',
            field=models.ManyToManyField(to='club.team'),
        ),
    ]
