# Generated by Django 4.1.7 on 2023-05-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='club',
        ),
    ]
