# Generated by Django 4.1.7 on 2023-05-22 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_matchday'),
        ('match', '0009_rename_groupteam1_match_group_team1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='league.matchday'),
            preserve_default=False,
        ),
    ]
