# Generated by Django 4.1.7 on 2023-04-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_backend', '0002_club_group_league_location_match_rol_team_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='league_id',
            new_name='league',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='club_id',
            new_name='club',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='club_id',
            new_name='club',
        ),
    ]
